# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
os: linux
dist: bionic  # distro used by Travis, moveit_ci uses the docker image's distro
services:
  - docker
language: cpp
cache: ccache
compiler: gcc

notifications:
  email: true

env:
  global:
    - MOVEIT_CI_TRAVIS_TIMEOUT=85  # Travis grants us 90 min, but we add a safety margin of 5 min
    - ROS_DISTRO=foxy
    - ROS_REPO=ros
    - UPSTREAM_WORKSPACE="moveit2_tutorials.repos, moveit2.repos"
    - CXXFLAGS="-Wall -Wextra -Wwrite-strings -Wunreachable-code -Wpointer-arith -Wredundant-decls"
    - WARNINGS_OK=false

jobs:
  fast_finish: true
  include:
    - name: "[Foxy] - htmlproofer"
      env: SCRIPT=htmlproofer.sh
    - name: "[Foxy] - clang-format, ament_lint"
      env: TEST="clang-format ament_lint"
    - name: "[Foxy] - gcc (build,test)"
      env: ROS_DISTRO=foxy

before_script:
  - git clone -q -b ros2 --depth=1 https://github.com/ros-planning/moveit_ci.git .moveit_ci

script:
  - .moveit_ci/travis.sh

deploy:
  # Deploy to gh-pages branch
  provider: pages
  # Don't delete built files
  skip-cleanup: true
  # Add to Environment Variables section of Travis CI repository settings page
  github-token: $GITHUB_TOKEN
  # Only copy build output directory to gh-pages
  local_dir: build
  on:
    branch: main
    condition: $SCRIPT = htmlproofer.sh
  fqdn: moveit2_tutorials.picknik.ai
